declare const styles: {
    readonly container: string;
    readonly SearchBar: string;
    readonly NavButton: string;
    readonly body: string;
    readonly sidenav: string;
    readonly footer: string;
    readonly searchBar: string;
    readonly button: string;
    readonly home: string;
    readonly header: string;
    readonly name: string;
    readonly main: string;
    readonly section: string;
    readonly article: string;
    readonly nombre: string;
    readonly block: string;
    readonly procesos: string;
    readonly sidebyside: string;
    readonly left: string;
    readonly right: string;
};
export = styles;
